name: build

on: [push, pull_request]

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build repair-rearm
        run: |
          cl "source/repair-rearm.c"
  build-windows-msvc-cpp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build repair-rearm
        run: |
          cl /Tp "source/repair-rearm.c"
  build-windows-tcc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: robinraju/release-downloader@v1
        with:
          repository: "mattiasgustavsson/tcc-build"
          tag: "tcc64"
          fileName: "tcc-0.9.27-win64-bin.zip"
      - name: extract tcc
        run: 7z x tcc-0.9.27-win64-bin.zip
      - name: build repair-rearm
        run: |
          tcc/tcc source/repair-rearm.c
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build repair-rearm
        run: |
          clang source/repair-rearm.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread -I$(brew --prefix glew)/include
  build-macos-cpp:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build repair-rearm
        run: |
          clang++ source/repair-rearm.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread -I$(brew --prefix glew)/include
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
          sudo apt-get install -qq libglew-dev
      - name: build repair-rearm
        run: |
          gcc source/repair-rearm.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
  build-linux-gcc-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
          sudo apt-get install -qq libglew-dev
      - name: build repair-rearm
        run: |
          gcc -xc++ source/repair-rearm.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
  build-wasm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: robinraju/release-downloader@v1
        with:
          repository: "mattiasgustavsson/template_project"
          tag: "wasm-build-tools"
          fileName: "wasm-build-tools-win.zip"
      - name: install dependencies
        run: 7z x wasm-build-tools-win.zip
      - name: build repair-rearm
        run: |          
            wasm\node wasm\wajicup.js source/repair-rearm.c repair-rearm.html
